"""add app_settings table

Revision ID: 17d5b5af8c03
Revises: 3bdbced4ba98
Create Date: 2026-07-28 00:21:31.835106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d5b5af8c03'
down_revision: Union[str, Sequence[str], None] = '3bdbced4ba98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


app_settings_table = sa.table(
    'app_settings',
    sa.column('id', sa.Integer()),
    sa.column('daily_new_card_limit', sa.Integer()),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_new_card_limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.bulk_insert(app_settings_table, [{'id': 1, 'daily_new_card_limit': 15}])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
