"""add srs scheduling fields and review_log

Revision ID: 3bdbced4ba98
Revises: d2f0916462fe
Create Date: 2026-07-24 19:51:27.567786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bdbced4ba98'
down_revision: Union[str, Sequence[str], None] = 'd2f0916462fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('grade', sa.Enum('again', 'hard', 'good', 'easy', name='reviewgrade', native_enum=False), nullable=False),
    sa.Column('interval_days_after', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_log_vocabulary_id'), 'review_log', ['vocabulary_id'], unique=False)
    op.add_column(
        'vocabulary',
        sa.Column('srs_interval_days', sa.Integer(), server_default='0', nullable=False),
    )
    op.add_column(
        'vocabulary',
        sa.Column('srs_ease_factor', sa.Float(), server_default='2.5', nullable=False),
    )
    op.add_column(
        'vocabulary',
        sa.Column('srs_repetitions', sa.Integer(), server_default='0', nullable=False),
    )
    op.add_column(
        'vocabulary',
        sa.Column('srs_lapses', sa.Integer(), server_default='0', nullable=False),
    )
    op.add_column('vocabulary', sa.Column('srs_next_review_at', sa.DateTime(), nullable=True))
    op.add_column('vocabulary', sa.Column('srs_last_reviewed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocabulary', 'srs_last_reviewed_at')
    op.drop_column('vocabulary', 'srs_next_review_at')
    op.drop_column('vocabulary', 'srs_lapses')
    op.drop_column('vocabulary', 'srs_repetitions')
    op.drop_column('vocabulary', 'srs_ease_factor')
    op.drop_column('vocabulary', 'srs_interval_days')
    op.drop_index(op.f('ix_review_log_vocabulary_id'), table_name='review_log')
    op.drop_table('review_log')
    # ### end Alembic commands ###
