"""add en_definition and subtitle_line

Revision ID: d2f0916462fe
Revises: eff9d22d5269
Create Date: 2026-07-24 17:13:10.398180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f0916462fe'
down_revision: Union[str, Sequence[str], None] = 'eff9d22d5269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtitle_line',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_log_id', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['media_log_id'], ['media_log.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtitle_line_media_log_id'), 'subtitle_line', ['media_log_id'], unique=False)
    op.add_column('vocabulary', sa.Column('en_definition', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocabulary', 'en_definition')
    op.drop_index(op.f('ix_subtitle_line_media_log_id'), table_name='subtitle_line')
    op.drop_table('subtitle_line')
    # ### end Alembic commands ###
