"""create media_log and vocabulary tables

Revision ID: eff9d22d5269
Revises: 
Create Date: 2026-07-24 16:09:40.971302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eff9d22d5269'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('language', sa.Enum('en', 'de', name='language', native_enum=False), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('watched_date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('duration_minutes >= 0', name='ck_media_log_duration_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_log_language'), 'media_log', ['language'], unique=False)
    op.create_table('vocabulary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('language', sa.Enum('en', 'de', name='language', native_enum=False), nullable=False),
    sa.Column('headword', sa.String(), nullable=False),
    sa.Column('part_of_speech', sa.String(), nullable=True),
    sa.Column('translation_zh', sa.Text(), nullable=True),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('media_log_id', sa.Integer(), nullable=True),
    sa.Column('ipa', sa.String(), nullable=True),
    sa.Column('de_artikel', sa.Enum('der', 'die', 'das', name='deartikel', native_enum=False), nullable=True),
    sa.Column('de_plural', sa.String(), nullable=True),
    sa.Column('de_conjugation', sa.Text(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['media_log_id'], ['media_log.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_headword'), 'vocabulary', ['headword'], unique=False)
    op.create_index(op.f('ix_vocabulary_language'), 'vocabulary', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocabulary_language'), table_name='vocabulary')
    op.drop_index(op.f('ix_vocabulary_headword'), table_name='vocabulary')
    op.drop_table('vocabulary')
    op.drop_index(op.f('ix_media_log_language'), table_name='media_log')
    op.drop_table('media_log')
    # ### end Alembic commands ###
